title: Eradicate The Thots
author: Gavin Forziati
description: > # this means to ignore newlines until "baseurl:"
  We are here for the removal of the thots from planet Earth.


show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
